#include "../src/blocks/t_piece.h"
#include "../src/blocks/long_piece.h"
#include "../src/blocks/square_piece.h"
#include "../src/blocks/l_left_piece.h"
#include "../src/blocks/l_right_piece.h"
#include "../src/blocks/snake_right_piece.h"